target 'MPParallaxCollection', :exclusive => true do
  pod "MPParallaxCollection", :path => "../"
pod "MPTextReveal"

end

target 'Tests', :exclusive => true do
  pod "MPParallaxCollection", :path => "../"
  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
